### ISSUE TITLE
Crash on resume?

### ISSUE THREAD

**Issue by micsthepick** [jbzdarkid/witness-trainer#16]
Suspended my Linux pc last afternoon, then on resume and tabbing back into the game, I needed to alt-f4 the game, because it black screened:

![image](https://github.com/jbzdarkid/witness-trainer/assets/11528421/2a3b02cc-52ac-4c81-acde-60cb99a3e49b)
(control c does nothing)

**Comment by jbzdarkid** [comment]
0x52023 0x52023 0x52218 0x537f2 0x1122e 0x52c98 0x53042 0x18c43 0x2d6ce 0xffffffff3b6146ed 0x3000f1c7

**Comment by jbzdarkid** [comment]
According to the callstack ReadProcessMemory failed while trying load the entity manager during the Heartbeat -- this means that we failed to read memory at a static address.

I'm really not sure how this happened, beyond something going critically wrong with the process handle. The trainer should have been suspended at that point, and not touching the game's memory at all (since the "heart" is not "beating", as it were).

Please let me know if it happens again, and I'll be happy to add some more debugging/logging to see if I can pinpoint the issue.
